{
 "title": "Bitbucket-slack-connector metrics",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Requests duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{job=\"bitbucket_slack_connector\", route=\"/bitbucket-webhook\"}/http_request_duration_seconds_count{job=\"bitbucket_slack_connector\", route=\"/bitbucket-webhook\"}",
     "legendFormat": "{{route}} (Status code {{status_code}})"
    },
    {
     "expr": "http_request_duration_seconds_sum{job=\"bitbucket_slack_connector\", route=\"/slack-channel\", status_code=\"200\"}/http_request_duration_seconds_count{job=\"bitbucket_slack_connector\", route=\"/slack-channel\", status_code=\"200\"}",
     "legendFormat": "{{route}} (Status code {{status_code}})"
    }
   ]
  },
  {
   "title": "Requests duration for \"bitbucket-webhook\" endpoint",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket{job=\"bitbucket_slack_connector\", route=\"/bitbucket-webhook\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests duration for \"slack-channel\" endpoint",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket{job=\"bitbucket_slack_connector\", route=\"/slack-channel\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests duration for \"bitbucket-webhook\" endpoint",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{job=\"bitbucket_slack_connector\", route=\"/bitbucket-webhook\"}[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests duration for \"slack-channel\" endpoint",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{job=\"bitbucket_slack_connector\", route=\"/slack-channel\"}[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Channel cache stats",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "channels_cache_utilized_size{job=\"bitbucket_slack_connector\"}",
     "legendFormat": "Utilized size"
    },
    {
     "expr": "channels_cache_hits{job=\"bitbucket_slack_connector\"}",
     "legendFormat": "Cache hits"
    },
    {
     "expr": "channels_cache_misses{job=\"bitbucket_slack_connector\"}",
     "legendFormat": "Cache misses"
    }
   ]
  },
  {
   "title": "Comments cache stats",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "comments_cache_utilized_size{job=\"bitbucket_slack_connector\"}",
     "legendFormat": "Utilized size"
    },
    {
     "expr": "comments_cache_hits{job=\"bitbucket_slack_connector\"}",
     "legendFormat": "Cache hits"
    },
    {
     "expr": "comments_cache_misses{job=\"bitbucket_slack_connector\"}",
     "legendFormat": "Cache misses"
    }
   ]
  }
 ]
}