{
 "title": "Merge-it-hot metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "endpoint_job_name_in_prometheus",
    "query": "${VAR_ENDPOINT_JOB_NAME_IN_PROMETHEUS}"
   },
   {
    "name": "route",
    "query": "/github-webhook, /slack-channel"
   },
   { "name": "cache", "query": "channels, userIds, comments" }
  ]
 },
 "panels": [
  {
   "title": "Requests duration for \"$route\" endpoint",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "repeat": "route",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_sum{job=\"$endpoint_job_name_in_prometheus\", route=\"$route\"}) by (job, status_code)/sum(http_request_duration_seconds_count{job=\"$endpoint_job_name_in_prometheus\", route=\"$route\"}) by (job, status_code)",
     "legendFormat": "{{route}} (Status code {{status_code}})"
    }
   ]
  },
  {
   "title": "Requests duration for \"$route\" endpoint",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "repeat": "route",
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{job=\"$endpoint_job_name_in_prometheus\", route=\"$route\"}[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache stats for ${cache}",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "repeat": "cache",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(${cache}_cache_utilized_size{job=\"$endpoint_job_name_in_prometheus\"}) by(job)",
     "legendFormat": "Utilized size"
    },
    {
     "expr": "sum(${cache}_cache_hits{job=\"$endpoint_job_name_in_prometheus\"}) by(job)",
     "legendFormat": "Cache hits"
    },
    {
     "expr": "sum(${cache}_cache_misses{job=\"$endpoint_job_name_in_prometheus\"}) by(job)",
     "legendFormat": "Cache misses"
    }
   ]
  },
  {
   "title": "App memory working set",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"$endpoint_job_name_in_prometheus\"}) by(job)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}