### Create pull request
POST http://localhost:3000/bitbucket-webhook
Content-Type: application/json

< ./PR-opened-test-payload.json

> {%
    client.assert(response.status === 200)
%}

### Add comment
POST http://localhost:3000/bitbucket-webhook
Content-Type: application/json

< ./PR-comment-added-test-payload.json

> {%
    client.assert(response.status === 200)
%}

### Modify PR
POST http://localhost:3000/bitbucket-webhook
Content-Type: application/json

< ./PR-modified-test-payload.json

> {%
    client.assert(response.status === 200)
%}

### Reviewer requested changes
POST http://localhost:3000/bitbucket-webhook
Content-Type: application/json

< ./PR-needs-work-test-payload.json

> {%
    client.assert(response.status === 200)
%}

### Reviewers list updated
POST http://localhost:3000/bitbucket-webhook
Content-Type: application/json

< ./PR-reviewer-updated-test-payload.json

> {%
    client.assert(response.status === 200)
%}

### Add commit
POST http://localhost:3000/bitbucket-webhook
Content-Type: application/json

< ./PR-from-ref-updated-test-payload.json

> {%
    client.assert(response.status === 200)
%}

### Reviewer approved pull request
POST http://localhost:3000/bitbucket-webhook
Content-Type: application/json

< ./PR-approved-test-payload.json

> {%
    client.assert(response.status === 200)
%}


### Merge pull request
POST http://localhost:3000/bitbucket-webhook
Content-Type: application/json

< ./PR-merged-test-payload.json

> {%
    client.assert(response.status === 200)
%}

### Invalid payload
POST http://localhost:3000/bitbucket-webhook
Content-Type: application/json

{
  "eventKey": "invalid-payload"
}

> {%
    client.assert(response.body === "Internal Server Error")
    client.assert(response.status === 500)
%}
