### Add comment to the pull request without channel
POST {{EndpointHost}}/bitbucket-webhook
Content-Type: application/json

< ./PR-comment-added-test-payload.json

> {%
    client.assert(response.body === "Internal Server Error")
    client.assert(response.status === 500)
%}

### Open pull request
POST {{EndpointHost}}/bitbucket-webhook
Content-Type: application/json

< ./PR-opened-test-payload.json

> {%
    client.assert(response.status === 200)
%}

### Add comment
POST {{EndpointHost}}/bitbucket-webhook
Content-Type: application/json

< ./PR-comment-added-test-payload.json

> {%
    client.assert(response.status === 200)
%}

### Edit comment
POST {{EndpointHost}}/bitbucket-webhook
Content-Type: application/json

< ./PR-comment-edited-test-payload.json

> {%
    client.assert(response.status === 200)
%}

### Delete comment
POST {{EndpointHost}}/bitbucket-webhook
Content-Type: application/json

< ./PR-comment-deleted-test-payload.json

> {%
    client.assert(response.status === 200)
%}

### Modify PR
POST {{EndpointHost}}/bitbucket-webhook
Content-Type: application/json

< ./PR-modified-test-payload.json

> {%
    client.assert(response.status === 200)
%}

### Reviewer requested changes
POST {{EndpointHost}}/bitbucket-webhook
Content-Type: application/json

< ./PR-needs-work-test-payload.json

> {%
    client.assert(response.status === 200)
%}

### Reviewers list updated
POST {{EndpointHost}}/bitbucket-webhook
Content-Type: application/json

< ./PR-reviewer-updated-test-payload.json

> {%
    client.assert(response.status === 200)
%}

### Add commit
POST {{EndpointHost}}/bitbucket-webhook
Content-Type: application/json

< ./PR-from-ref-updated-test-payload.json

> {%
    client.assert(response.status === 200)
%}

### Reviewer approved pull request
POST {{EndpointHost}}/bitbucket-webhook
Content-Type: application/json

< ./PR-approved-test-payload.json

> {%
    client.assert(response.status === 200)
%}


### Merge pull request
POST {{EndpointHost}}/bitbucket-webhook
Content-Type: application/json

< ./PR-merged-test-payload.json

> {%
    client.assert(response.status === 200)
%}

### Invalid payload
POST {{EndpointHost}}/bitbucket-webhook
Content-Type: application/json

{
  "eventKey": "invalid-payload"
}

> {%
    client.assert(response.body === "Internal Server Error")
    client.assert(response.status === 500)
%}

### Add comment to the already closed pull request
POST {{EndpointHost}}/bitbucket-webhook
Content-Type: application/json

< ./PR-comment-added-test-payload.json

> {%
    client.assert(response.body === "Internal Server Error")
    client.assert(response.status === 500)
%}
