### Open pull request
POST {{EndpointHost}}/github-webhook
Content-Type: application/json

< ./test-payloads/PR-opened-test-payload.json

> {%
    client.test("Pull request opening should be successful", function() {
        client.assert(response.status === 200);
    });
%}

### Add reviewer
POST {{EndpointHost}}/github-webhook
Content-Type: application/json

< ./test-payloads/PR-review-requested-test-payload.json

> {%
    client.test("Adding reviewer to the open Pull request should be successful", function() {
        client.assert(response.status === 200);
    });
%}

### Change to another reviewer
POST {{EndpointHost}}/github-webhook
Content-Type: application/json

< ./test-payloads/PR-review-request-changed-test-payload.json

> {%
    client.test("Changing reviewer for the open Pull request should be successful", function() {
        client.assert(response.status === 200);
    });
%}

### Add commit
POST {{EndpointHost}}/github-webhook
Content-Type: application/json

< ./test-payloads/PR-synchronized-test-payload.json

> {%
    client.test("Adding commit to the open Pull request should be successful", function() {
        client.assert(response.status === 200);
    });
%}

### Add assignee
POST {{EndpointHost}}/github-webhook
Content-Type: application/json

< ./test-payloads/PR-assigned-test-payload.json

> {%
    client.test("Adding assignee to the open Pull request should be successful", function() {
        client.assert(response.status === 200);
    });
%}

### Remove assignee
POST {{EndpointHost}}/github-webhook
Content-Type: application/json

< ./test-payloads/PR-unassigned-test-payload.json

> {%
    client.test("Removing assignee from the open Pull request should be successful", function() {
        client.assert(response.status === 200);
    });
%}


### Merge pull request
POST {{EndpointHost}}/github-webhook
Content-Type: application/json

< ./test-payloads/PR-merged-test-payload.json

> {%
    client.test("Pull request merge should be successful", function() {
        client.assert(response.status === 200);
    });
%}

### Invalid payload
POST {{EndpointHost}}/github-webhook
Content-Type: application/json

{
  "eventKey": "invalid-payload"
}

> {%
    client.test("Invalid payload sending should lead to error", function() {
        console.log(response.body)
        client.assert(response.body.indexOf('"undefined" action key is unknown') !== -1);
        client.assert(response.status === 500)
    });
%}