### Open pull request
POST {{EndpointHost}}/github-webhook
Content-Type: application/json
X-GitHub-Event: pull_request

< ./test-payloads/PR-opened-test-payload.json

> {%
    client.test("Pull request opening should be successful", function() {
        client.assert(response.status === 200);
    });
%}

### Add reviewer
POST {{EndpointHost}}/github-webhook
Content-Type: application/json
X-GitHub-Event: pull_request

< ./test-payloads/PR-review-requested-test-payload.json

> {%
    client.test("Adding reviewer to the open Pull request should be successful", function() {
        client.assert(response.status === 200);
    });
%}

### Add Issue-level comment
POST {{EndpointHost}}/github-webhook
Content-Type: application/json
X-GitHub-Event: issue_comment

< ./test-payloads/Issue-comment-created.json

> {%
    client.test("Adding Issue comment to the open Pull request should be successful", function() {
        client.assert(response.status === 200);
    });
%}


### Add comment
POST {{EndpointHost}}/github-webhook
Content-Type: application/json
X-GitHub-Event: pull_request_review_comment

< ./test-payloads/PR-comment-created-test-payload.json

> {%
    client.test("Adding comment to the open Pull request should be successful", function() {
        client.assert(response.status === 200);
    });
%}

### Reply to comment
POST {{EndpointHost}}/github-webhook
Content-Type: application/json
X-GitHub-Event: pull_request_review_comment

< ./test-payloads/PR-comment-replied-test-payload.json

> {%
    client.test("Replying to the comment should be successful", function() {
        client.assert(response.status === 200);
    });
%}

### Edit comment
POST {{EndpointHost}}/github-webhook
Content-Type: application/json
X-GitHub-Event: pull_request_review_comment

< ./test-payloads/PR-comment-edited-test-payload.json

> {%
    client.test("Edit of the comment should be successful", function() {
        client.assert(response.status === 200);
    });
%}

### Resolve thread
POST {{EndpointHost}}/github-webhook
Content-Type: application/json
X-GitHub-Event: pull_request_review_thread

< ./test-payloads/PR-thread-resolved-test-payload.json

> {%
    client.test("Thread resolution should be successful", function() {
        client.assert(response.status === 200);
    });
%}

### Unresolve thread
POST {{EndpointHost}}/github-webhook
Content-Type: application/json
X-GitHub-Event: pull_request_review_thread

< ./test-payloads/PR-thread-unresolved-test-payload.json

> {%
    client.test("Thread unresolving should be successful", function() {
        client.assert(response.status === 200);
    });
%}

### Delete comment
POST {{EndpointHost}}/github-webhook
Content-Type: application/json
X-GitHub-Event: pull_request_review_comment

< ./test-payloads/PR-comment-deleted-test-payload.json

> {%
    client.test("Deletion of the comment should be successful", function() {
        client.assert(response.status === 200);
    });
%}

### Remove reviewer
POST {{EndpointHost}}/github-webhook
Content-Type: application/json
X-GitHub-Event: pull_request

< ./test-payloads/PR-review-request-removed-test-payload.json

> {%
    client.test("Removing reviewer for the open Pull request should be successful", function() {
        client.assert(response.status === 200);
    });
%}

### Add commit
POST {{EndpointHost}}/github-webhook
Content-Type: application/json
X-GitHub-Event: pull_request

< ./test-payloads/PR-synchronized-test-payload.json

> {%
    client.test("Adding commit to the open Pull request should be successful", function() {
        client.assert(response.status === 200);
    });
%}

### Set as ready for review
POST {{EndpointHost}}/github-webhook
Content-Type: application/json
X-GitHub-Event: pull_request

< ./test-payloads/PR-ready-for-review-test-payload.json

> {%
    client.test("Set as ready for review should be successful", function() {
        client.assert(response.status === 200);
    });
%}

### Add assignee
POST {{EndpointHost}}/github-webhook
Content-Type: application/json
X-GitHub-Event: pull_request

< ./test-payloads/PR-assigned-test-payload.json

> {%
    client.test("Adding assignee to the open Pull request should be successful", function() {
        client.assert(response.status === 200);
    });
%}

### Edit pull request
POST {{EndpointHost}}/github-webhook
Content-Type: application/json
X-GitHub-Event: pull_request

< ./test-payloads/PR-edited-test-payload.json

> {%
    client.test("Editing PR information about body, title, and base href should be successful", function() {
        client.assert(response.status === 200);
    });
%}

### Remove assignee
POST {{EndpointHost}}/github-webhook
Content-Type: application/json
X-GitHub-Event: pull_request

< ./test-payloads/PR-unassigned-test-payload.json

> {%
    client.test("Removing assignee from the open Pull request should be successful", function() {
        client.assert(response.status === 200);
    });
%}

### Submit review
POST {{EndpointHost}}/github-webhook
Content-Type: application/json
X-GitHub-Event: pull_request_review

< ./test-payloads/PR-review-submitted-test-payload.json

> {%
    client.test("Submitting review to the open Pull request should be successful", function() {
        client.assert(response.status === 200);
    });
%}


### Merge pull request
POST {{EndpointHost}}/github-webhook
Content-Type: application/json
X-GitHub-Event: pull_request

< ./test-payloads/PR-merged-test-payload.json

> {%
    client.test("Pull request merge should be successful", function() {
        client.assert(response.status === 200);
    });
%}

### Add comment to the already closed pull request
POST {{EndpointHost}}/github-webhook
Content-Type: application/json
X-GitHub-Event: pull_request_review_comment

< ./test-payloads/PR-comment-created-test-payload.json

> {%
    client.test("Addition of the comment to closed PR should unarchive the channel and send the message", function() {
        client.assert(response.status === 200);
    });
%}


### Invalid payload
POST {{EndpointHost}}/github-webhook
Content-Type: application/json
X-GitHub-Event: pull_request

{
  "action": "invalid-payload",
  "organization": {
    "id": "{{OrganizationId}}"
  }
}

> {%
    client.test("Invalid payload sending should lead to error", function() {
        console.log(response.body)
        client.assert(response.body.indexOf('"invalid-payload" action key is unknown') !== -1);
        client.assert(response.status === 500)
    });
%}