name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ vars.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd app/merge-it-hot
            docker compose pull
            docker compose down
            docker-compose up -d
